### ISSUE TITLE
Indicator ring not shown

### ISSUE THREAD

**Issue by mnussbaum** [mortie/swaylock-effects#53]
I've noticed that the indicator ring isn't showing when swaylock-effects is activated since moving to latest wlroots-git and sway-git from the AUR as of March 9th. The screen still locks and unlocks properly, just the indicator ring is missing. If I use a secondary monitor however the indicator ring does show on that monitor. Also, swaylock upstream properly shows the ring. I wonder there are upstream commits that need to be pulled in? I'm currently using latest of swaylock-effects-git from the AUR

Let me know if there's any more info I can provide or anything else I can do to help debug! Thanks!

**Comment by trobjo** [comment]
I have the same problem, and I cannot get the clock to show either.

**Comment by mortie** [comment]
I wasn't able to reproduce this using the latest sway and the latest wlroots. What's the exact command you're running?

There are 3 commits to upstream Swaylock which I haven't merged yet. None of them seem obviously connected, but I did make a branch where I merged in those changes: https://github.com/mortie/swaylock-effects/tree/merge - Could you test that and see if it fixes the issue?

**Comment by mnussbaum** [comment]
I'm just running `swaylock` directly and can replicate this. I tested with the merge branch but unfortunately am still seeing the issue.

Interestingly, if I lock the screen with my external monitor unplugged, and then plug the external monitor in then the ring shows on the external monitor when it activates. It seems like swaylock is somehow tied to the external monitor's output. I don't know why that would be the case though

**Comment by minhduc0711** [comment]
@mnussbaum iirc the indicator used to appear on all monitors.
I have tried the original `swaylock-git` as well and still can reproduce, so I guess this might be an upstream bug.

**Comment by mnussbaum** [comment]
FWIW I'm not able to repro this with upstream swaylock-git

**Comment by minhduc0711** [comment]
Do you happen to have scaling != 1.0 on your laptop display?

**Comment by mnussbaum** [comment]
Indeed I do use a `scale 2` on the output the ring is hidden on! When I switch back to `scale 1` the ring is shown correctly. Good find!

**Comment by GamerPanda99** [comment]
Just to add to this. Could reproduce the effect of  `scale != 1.0` too. I also noticed that setting anything that forces the indicator to be shown (eg `--indicator --indicator-idle-visible`) causes it to show up regardless of DPI scaling.

**Comment by GamerPanda99** [comment]
Also setting `grace` to anything higher than 0 seems to hide the indicator if used with `--indicator-idle-visible`. I hope this helps.

**Comment by minhduc0711** [comment]
Setting `--indicator-idle-visible` makes it appear, but it would be gone right as I start typing.

**Comment by plabadens** [comment]
Amusingly, swaywm/swaylock#187 is supposed to fix this issue, but applying that patch on top of this fork does not seem to change anything. It seems to be caused by some interaction between the changes introduced in this fork and the scaling factor set with in sway.

**Comment by minhduc0711** [comment]
Quoting myself from another thread https://github.com/swaywm/swaylock/issues/168#issuecomment-877220065

The rings on `swaylock-effects` are also appearing for me.

**Comment by plabadens** [comment]
Nevermind, it seems to work on top of latest master.
